version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    username: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_USERNAME}}"
    password: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - dependency
  ignore:
  - dependency-name: "@nuxtjs/gtm"
    versions:
    - 2.4.0
  - dependency-name: cross-env
    versions:
    - 7.0.3
  - dependency-name: vue-slick
    versions:
    - 1.1.16
  - dependency-name: tar
    versions:
    - 6.1.0
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.4.0
    - 7.5.0
    - 7.6.0
  - dependency-name: "@nuxtjs/eslint-config"
    versions:
    - 4.0.0
  - dependency-name: nuxt
    versions:
    - 2.14.12
    - 2.15.2
  - dependency-name: nodemon
    versions:
    - 2.0.6
    - 2.0.7
  - dependency-name: "@fullcalendar/daygrid"
    versions:
    - 5.5.0
  - dependency-name: "@fullcalendar/vue"
    versions:
    - 5.5.0
  - dependency-name: "@fullcalendar/core"
    versions:
    - 5.5.0
    - 5.5.1
  - dependency-name: node-sass
    versions:
    - 5.0.0
  - dependency-name: axios
    versions:
    - 0.21.1
  - dependency-name: sass-loader
    versions:
    - 10.1.0
    - 10.1.1
  registries:
  - npm-registry-npm-pkg-github-com
